<../../mkconfig

TARG=\
	cgi.dis\
	htmlent.dis\
	ohttp.dis\
	template.dis\
	netstr.dis\
	rssgen.dis\

MODULES=\

SYSMODULES=\
	asn1.m\
	bufio.m\
	daytime.m\
	dict.m\
	encoding.m\
	env.m\
	filter.m\
	keyring.m\
	pkcs.m\
	regex.m\
	security.m\
	ssl3.m\
	sslsession.m\
	string.m\
	sys.m\
	cgi.m\
	htmlent.m\
	netstr.m\
	ohttp.m\
	rssgen.m\
	template.m\


DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
