<../../mkconfig

TARG=\
	scgils.dis\
	cgienv.dis\
	testcgi.dis\
	testhtmlent.dis\
	testtemplate2.dis\
	testtemplate.dis\
	readnetstr.dis\
	testnetstr.dis\
	writenetstr.dis\
	testrssgen.dis\
	cgiparse.dis\

SYSMODULES=\
	arg.m\
	bufio.m\
	cgi.m\
	draw.m\
	env.m\
	htmlent.m\
	lists.m\
	netstr.m\
	rssgen.m\
	string.m\
	sys.m\
	template.m\

DISBIN=$ROOT/dis

<$ROOT/mkfiles/mkdis
